name: ci

on:
  push:
    branches:
      - "master"



env:
  BASE_IMAGE: sadraiiali/rcss2d-grpc-base
  BASE_TAG: ubuntu-24.04

  AGENT_IMAGE: sadraiiali/rcss2d-grpc-agent
  AGENT_TAG: latest
jobs:
  check:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      base_changed: ${{ steps.filter.outputs.base }}
      code_changed: ${{ steps.filter.outputs.code }}
      base_readme_changed: ${{ steps.filter.outputs.base_readme }}
      agent_readme_changed: ${{ steps.filter.outputs.agent_readme }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            base:
              - 'images/rcss2d-grpc-base/**'
              - '!images/rcss2d-grpc-agent/README.md'
            base_readme:
              - 'images/rcss2d-grpc-base/README.md'
            code:
              - 'grpc/**'
              - 'images/rcss2d-grpc-agent/**'
              - '!images/rcss2d-grpc-agent/README.md'
              - 'm4/**'
              - 'src/**'
              - 'ssil/**'
              - 'cmake-config.h.in'
              - 'CMakeLists.txt'
            agent_readme:
              - 'images/rcss2d-grpc-agent/README.md'

  base:
    needs: check
    runs-on: ubuntu-latest
    name: Build & Push GRPC Build Base
    steps:
      - name: Checkout
        if: needs.check.outputs.base_changed == 'true'
        uses: actions/checkout@v4
      - name: Set up QEMU
        if: needs.check.outputs.base_changed == 'true'
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        if: needs.check.outputs.base_changed == 'true'
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: needs.check.outputs.base_changed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push GRPC Build Base
        if: needs.check.outputs.base_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./images/rcss2d-grpc-base/Dockerfile
          push: true
          tags: "${{ env.BASE_IMAGE }}:${{ env.BASE_TAG }}"

      - name: Docker Hub Description
        if: needs.check.outputs.base_readme_changed == 'true'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.BASE_IMAGE }}
          readme-filepath : ./images/rcss2d-grpc-base/README.md
          short-description: "Base image for build rcss2d-grpc-agent"

  agent:
    needs: [check,base]
    if: needs.check.outputs.code_changed == 'true' || needs.check.outputs.agent_readme_changed == 'true'  || needs.check.outputs.base_changed == 'true'
    runs-on: ubuntu-latest
    name: Build & Push GRPC Agent
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        if: needs.check.outputs.code_changed == 'true'  || needs.check.outputs.base_changed == 'true'
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        if: needs.check.outputs.code_changed == 'true'  || needs.check.outputs.base_changed == 'true'
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: needs.check.outputs.code_changed == 'true'  || needs.check.outputs.base_changed == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push GRPC Agent
        if: needs.check.outputs.code_changed == 'true'  || needs.check.outputs.base_changed == 'true' 
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./images/rcss2d-grpc-agent/Dockerfile
          push: true
          tags: "${{ env.AGENT_IMAGE }}:${{ env.AGENT_TAG }}"
      
        
      - name: Docker Hub Description
        if: needs.check.outputs.agent_readme_changed == 'true'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.AGENT_IMAGE }}
          readme-filepath : ./images/rcss2d-grpc-agent/README.md
          short-description: "Agent image for rcss2d-grpc-server"
