name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  check:
    name: Check for base changes
    runs-on: ubuntu-latest
    outputs:
      base_changed: ${{ steps.filter.outputs.base_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            base:
              - 'images/rcss2d-grpc-base/**'

  base:
    needs: check
    if: needs.check.outputs.base_changed == 'true'
    runs-on: ubuntu-latest
    name: Build & Push GRPC Build Base
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push GRPC Build Base
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./images/rcss2d-grpc-base/Dockerfile
          push: true
          tags: sadraiiali/rcss2d-grpc-base:ubuntu-24.04
            
  agent:
    needs: [check, base]
    runs-on: ubuntu-latest
    name: Build & Push GRPC Agent
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push GRPC Agent
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./images/rcss2d-grpc-agent/Dockerfile
          push: true
          tags: sadraiiali/rcss2d-grpc-agent:latest