name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  check:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      base_changed: ${{ steps.filter.outputs.base }}
      code_changed: ${{ steps.filter.outputs.code }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            base:
              - 'images/rcss2d-grpc-base/**'
            code:
              - 'grpc/**'
              - 'images/rcss2d-grpc-agent/**'
              - 'm4/**'
              - 'src/**'
              - 'ssil/**'
              - 'cmake-config.h.in'
              - 'CMakeLists.txt'
            

  base:
    needs: check
    if: needs.check.outputs.base_changed == 'true'
    runs-on: ubuntu-latest
    name: Build & Push GRPC Build Base
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push GRPC Build Base
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./images/rcss2d-grpc-base/Dockerfile
          push: true
          tags: sadraiiali/rcss2d-grpc-base:ubuntu-24.04
            
  agent:
    needs: check
    if: needs.check.outputs.code_changed == 'true'
    runs-on: ubuntu-latest
    name: Build & Push GRPC Agent
    steps:
      - if: needs.check.outputs.base_changed == 'true'
        uses: actions/wait-for-check-action@v1.1.0
        id: wait-for-build
        with:
          ref: ${{ github.ref }}
          checkName: "Build & Push GRPC Build Base"
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          timeoutSeconds: 600
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push GRPC Agent
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./images/rcss2d-grpc-agent/Dockerfile
          push: true
          tags: sadraiiali/rcss2d-grpc-agent:latest